export const sample_repos = {
  viewer: {
    repositories: {
      edges: [
        {
          cursor: "Y3Vyc29yOnYyOpHOF4F_Uw==",
          node: {
            id: "MDEwOlJlcG9zaXRvcnkzOTQzNjI3MDc=",
            name: "edit-table",
            viewerPermission: "ADMIN",
            nameWithOwner: "tigawanna/edit-table",
            description: "table with dynamic editable rows",
            url: "https://github.com/tigawanna/edit-table",
            openGraphImageUrl:
              "https://opengraph.githubassets.com/e00641b36b784b8587a41bc54ae4ea7ceef07b92a1ac3d30103d64328cd18aea/tigawanna/edit-table",
            updatedAt: "2022-04-25T09:48:36Z",
            isFork: false,
            isPrivate: false,
            isTemplate: false,
            isArchived: false,
            isEmpty: false,
            forkCount: 0,
            stargazerCount: 0,
            viewerCanUpdateTopics: true,
            viewerCanAdminister: true,
            repositoryTopics: {
              nodes: [],
            },
          },
        },
        {
          cursor: "Y3Vyc29yOnYyOpHOF-ehNw==",
          node: {
            id: "MDEwOlJlcG9zaXRvcnk0MDEwNTYwNTU=",
            name: "react-native-music-player-with-expo",
            viewerPermission: "ADMIN",
            nameWithOwner: "tigawanna/react-native-music-player-with-expo",
            description: "react antive expo music player",
            url: "https://github.com/tigawanna/react-native-music-player-with-expo",
            openGraphImageUrl:
              "https://opengraph.githubassets.com/856028e811073399b0148c1a689e9e0bf4de206540d822edb7ae30db1fcaf26d/tigawanna/react-native-music-player-with-expo",
            updatedAt: "2021-08-29T14:04:00Z",
            isFork: false,
            isPrivate: false,
            isTemplate: true,
            isArchived: false,
            isEmpty: false,
            forkCount: 0,
            stargazerCount: 0,
            viewerCanUpdateTopics: true,
            viewerCanAdminister: true,
            repositoryTopics: {
              nodes: [],
            },
          },
        },
        {
          cursor: "Y3Vyc29yOnYyOpHOGLGY4Q==",
          node: {
            id: "R_kgDOGLGY4Q",
            name: "music-player-java",
            viewerPermission: "ADMIN",
            nameWithOwner: "tigawanna/music-player-java",
            description: "simple music player made with java ",
            url: "https://github.com/tigawanna/music-player-java",
            openGraphImageUrl:
              "https://opengraph.githubassets.com/dfd77989ff62690961dfc63e6eb34d3dbe4842f8d79b571c53ee4094cba4612a/tigawanna/music-player-java",
            updatedAt: "2021-10-07T22:05:51Z",
            isFork: false,
            isPrivate: false,
            isTemplate: false,
            isArchived: false,
            isEmpty: false,
            forkCount: 1,
            stargazerCount: 0,
            viewerCanUpdateTopics: true,
            viewerCanAdminister: true,
            repositoryTopics: {
              nodes: [],
            },
          },
        },
        {
          cursor: "Y3Vyc29yOnYyOpHOGYHsXA==",
          node: {
            id: "R_kgDOGYHsXA",
            name: "lireddit",
            viewerPermission: "ADMIN",
            nameWithOwner: "tigawanna/lireddit",
            description: null,
            url: "https://github.com/tigawanna/lireddit",
            openGraphImageUrl:
              "https://opengraph.githubassets.com/04fd726cf7cc5457e242a68ff028c57a0d9190e3516506a6492149d778c95dbf/tigawanna/lireddit",
            updatedAt: "2022-01-03T06:21:38Z",
            isFork: false,
            isPrivate: false,
            isTemplate: false,
            isArchived: false,
            isEmpty: false,
            forkCount: 1,
            stargazerCount: 0,
            viewerCanUpdateTopics: true,
            viewerCanAdminister: true,
            repositoryTopics: {
              nodes: [],
            },
          },
        },
        {
          cursor: "Y3Vyc29yOnYyOpHOGZHaLw==",
          node: {
            id: "R_kgDOGZHaLw",
            name: "property",
            viewerPermission: "ADMIN",
            nameWithOwner: "tigawanna/property",
            description: null,
            url: "https://github.com/tigawanna/property",
            openGraphImageUrl:
              "https://avatars.githubusercontent.com/u/72096712?s=400&v=4",
            updatedAt: "2021-11-17T09:48:08Z",
            isFork: false,
            isPrivate: true,
            isTemplate: false,
            isArchived: false,
            isEmpty: false,
            forkCount: 0,
            stargazerCount: 0,
            viewerCanUpdateTopics: true,
            viewerCanAdminister: true,
            repositoryTopics: {
              nodes: [],
            },
          },
        },
        {
          cursor: "Y3Vyc29yOnYyOpHOGiSmJw==",
          node: {
            id: "R_kgDOGiSmJw",
            name: "prices",
            viewerPermission: "ADMIN",
            nameWithOwner: "tigawanna/prices",
            description: null,
            url: "https://github.com/tigawanna/prices",
            openGraphImageUrl:
              "https://avatars.githubusercontent.com/u/72096712?s=400&v=4",
            updatedAt: "2022-02-10T16:53:25Z",
            isFork: false,
            isPrivate: true,
            isTemplate: false,
            isArchived: false,
            isEmpty: false,
            forkCount: 0,
            stargazerCount: 0,
            viewerCanUpdateTopics: true,
            viewerCanAdminister: true,
            repositoryTopics: {
              nodes: [],
            },
          },
        },
        {
          cursor: "Y3Vyc29yOnYyOpHOGnBLpw==",
          node: {
            id: "R_kgDOGnBLpw",
            name: "chat",
            viewerPermission: "ADMIN",
            nameWithOwner: "tigawanna/chat",
            description: null,
            url: "https://github.com/tigawanna/chat",
            openGraphImageUrl:
              "https://opengraph.githubassets.com/29425716416d9748dbf45e75f16b77d430e3aad3bc07d9f85013c6b2cad2272c/tigawanna/chat",
            updatedAt: "2022-01-07T04:15:05Z",
            isFork: false,
            isPrivate: false,
            isTemplate: false,
            isArchived: false,
            isEmpty: false,
            forkCount: 0,
            stargazerCount: 0,
            viewerCanUpdateTopics: true,
            viewerCanAdminister: true,
            repositoryTopics: {
              nodes: [],
            },
          },
        },
        {
          cursor: "Y3Vyc29yOnYyOpHOGwLvGg==",
          node: {
            id: "R_kgDOGwLvGg",
            name: "bills",
            viewerPermission: "ADMIN",
            nameWithOwner: "tigawanna/bills",
            description: null,
            url: "https://github.com/tigawanna/bills",
            openGraphImageUrl:
              "https://avatars.githubusercontent.com/u/72096712?s=400&v=4",
            updatedAt: "2022-01-28T18:34:38Z",
            isFork: false,
            isPrivate: true,
            isTemplate: false,
            isArchived: false,
            isEmpty: true,
            forkCount: 0,
            stargazerCount: 0,
            viewerCanUpdateTopics: true,
            viewerCanAdminister: true,
            repositoryTopics: {
              nodes: [],
            },
          },
        },
        {
          cursor: "Y3Vyc29yOnYyOpHOGwLvUQ==",
          node: {
            id: "R_kgDOGwLvUQ",
            name: "bills-master",
            viewerPermission: "ADMIN",
            nameWithOwner: "tigawanna/bills-master",
            description: null,
            url: "https://github.com/tigawanna/bills-master",
            openGraphImageUrl:
              "https://avatars.githubusercontent.com/u/72096712?s=400&v=4",
            updatedAt: "2022-01-28T18:35:02Z",
            isFork: false,
            isPrivate: true,
            isTemplate: false,
            isArchived: false,
            isEmpty: false,
            forkCount: 0,
            stargazerCount: 0,
            viewerCanUpdateTopics: true,
            viewerCanAdminister: true,
            repositoryTopics: {
              nodes: [],
            },
          },
        },
        {
          cursor: "Y3Vyc29yOnYyOpHOG14zsQ==",
          node: {
            id: "R_kgDOG14zsQ",
            name: "property-ts-v9",
            viewerPermission: "ADMIN",
            nameWithOwner: "tigawanna/property-ts-v9",
            description: null,
            url: "https://github.com/tigawanna/property-ts-v9",
            openGraphImageUrl:
              "https://avatars.githubusercontent.com/u/72096712?s=400&v=4",
            updatedAt: "2022-02-14T12:45:21Z",
            isFork: false,
            isPrivate: true,
            isTemplate: false,
            isArchived: false,
            isEmpty: false,
            forkCount: 0,
            stargazerCount: 0,
            viewerCanUpdateTopics: true,
            viewerCanAdminister: true,
            repositoryTopics: {
              nodes: [],
            },
          },
        },
        {
          cursor: "Y3Vyc29yOnYyOpHOG2io3w==",
          node: {
            id: "R_kgDOG2io3w",
            name: "alx-pre_course",
            viewerPermission: "ADMIN",
            nameWithOwner: "tigawanna/alx-pre_course",
            description:
              "I'm now a ALX Student, this is my first repository as a full-stack engineer",
            url: "https://github.com/tigawanna/alx-pre_course",
            openGraphImageUrl:
              "https://opengraph.githubassets.com/601004ac3c3616e4b063c9c4862c5dc13d21adf98387537764a5c42ab0638a16/tigawanna/alx-pre_course",
            updatedAt: "2022-02-17T03:41:58Z",
            isFork: false,
            isPrivate: false,
            isTemplate: false,
            isArchived: false,
            isEmpty: false,
            forkCount: 0,
            stargazerCount: 0,
            viewerCanUpdateTopics: true,
            viewerCanAdminister: true,
            repositoryTopics: {
              nodes: [],
            },
          },
        },
        {
          cursor: "Y3Vyc29yOnYyOpHOG64nrQ==",
          node: {
            id: "R_kgDOG64nrQ",
            name: "zero_day",
            viewerPermission: "ADMIN",
            nameWithOwner: "tigawanna/zero_day",
            description: "This is my first repository as a full-stack engineer",
            url: "https://github.com/tigawanna/zero_day",
            openGraphImageUrl:
              "https://opengraph.githubassets.com/f29de05053b2aa4200bded6374960e6c93206728775260d8f09ee27e25d96d02/tigawanna/zero_day",
            updatedAt: "2022-02-28T08:30:06Z",
            isFork: false,
            isPrivate: false,
            isTemplate: false,
            isArchived: false,
            isEmpty: false,
            forkCount: 0,
            stargazerCount: 0,
            viewerCanUpdateTopics: true,
            viewerCanAdminister: true,
            repositoryTopics: {
              nodes: [],
            },
          },
        },
        {
          cursor: "Y3Vyc29yOnYyOpHOG7PR3A==",
          node: {
            id: "R_kgDOG7PR3A",
            name: "alx-zero_day",
            viewerPermission: "ADMIN",
            nameWithOwner: "tigawanna/alx-zero_day",
            description:
              "I'm now a ALX Student, this is my first repository as a full-stack engineer",
            url: "https://github.com/tigawanna/alx-zero_day",
            openGraphImageUrl:
              "https://opengraph.githubassets.com/2b39c30e6bfb9e51e9160b2a1aee7a64420f5bb418fa7ec1bf9944e3969fa547/tigawanna/alx-zero_day",
            updatedAt: "2022-03-01T07:16:37Z",
            isFork: false,
            isPrivate: false,
            isTemplate: false,
            isArchived: false,
            isEmpty: false,
            forkCount: 0,
            stargazerCount: 0,
            viewerCanUpdateTopics: true,
            viewerCanAdminister: true,
            repositoryTopics: {
              nodes: [],
            },
          },
        },
        {
          cursor: "Y3Vyc29yOnYyOpHOG7o3yg==",
          node: {
            id: "R_kgDOG7o3yg",
            name: "alx-system_engineering-devops",
            viewerPermission: "ADMIN",
            nameWithOwner: "tigawanna/alx-system_engineering-devops",
            description: "bash scripting alx",
            url: "https://github.com/tigawanna/alx-system_engineering-devops",
            openGraphImageUrl:
              "https://opengraph.githubassets.com/9fc39e4eb67d2e5d72c0bae7c1d2a12488215caea73461168590a45aafc22295/tigawanna/alx-system_engineering-devops",
            updatedAt: "2022-03-02T07:20:43Z",
            isFork: false,
            isPrivate: false,
            isTemplate: false,
            isArchived: false,
            isEmpty: false,
            forkCount: 1,
            stargazerCount: 0,
            viewerCanUpdateTopics: true,
            viewerCanAdminister: true,
            repositoryTopics: {
              nodes: [],
            },
          },
        },
        {
          cursor: "Y3Vyc29yOnYyOpHOG-qVrQ==",
          node: {
            id: "R_kgDOG-qVrQ",
            name: "alx-low_level_programming",
            viewerPermission: "ADMIN",
            nameWithOwner: "tigawanna/alx-low_level_programming",
            description: null,
            url: "https://github.com/tigawanna/alx-low_level_programming",
            openGraphImageUrl:
              "https://opengraph.githubassets.com/9b6005557957bd5fc05310934f52ac57a7ef3b9e879292e7e08d72a910ce04d6/tigawanna/alx-low_level_programming",
            updatedAt: "2022-03-10T19:34:13Z",
            isFork: false,
            isPrivate: false,
            isTemplate: false,
            isArchived: false,
            isEmpty: false,
            forkCount: 4,
            stargazerCount: 0,
            viewerCanUpdateTopics: true,
            viewerCanAdminister: true,
            repositoryTopics: {
              nodes: [],
            },
          },
        },
        {
          cursor: "Y3Vyc29yOnYyOpHOHMHBLg==",
          node: {
            id: "R_kgDOHMHBLg",
            name: "printf",
            viewerPermission: "ADMIN",
            nameWithOwner: "tigawanna/printf",
            description: "alx-low-level-printf",
            url: "https://github.com/tigawanna/printf",
            openGraphImageUrl:
              "https://opengraph.githubassets.com/bfccbedb52ed584ad2b07bdeb4e174917ba930f033759a4601b1128f547cb06b/tigawanna/printf",
            updatedAt: "2022-04-18T07:11:04Z",
            isFork: false,
            isPrivate: false,
            isTemplate: false,
            isArchived: false,
            isEmpty: false,
            forkCount: 1,
            stargazerCount: 0,
            viewerCanUpdateTopics: true,
            viewerCanAdminister: true,
            repositoryTopics: {
              nodes: [],
            },
          },
        },
        {
          cursor: "Y3Vyc29yOnYyOpHOHQu4Yw==",
          node: {
            id: "R_kgDOHQu4Yw",
            name: "tigawanna",
            viewerPermission: "ADMIN",
            nameWithOwner: "tigawanna/tigawanna",
            description: "more about dennis kinuthia",
            url: "https://github.com/tigawanna/tigawanna",
            openGraphImageUrl:
              "https://opengraph.githubassets.com/b152522c96c9dcd3a97b5421bdabf4f26bbc23c2d04cd8b81b57bbdc636ca4da/tigawanna/tigawanna",
            updatedAt: "2023-06-22T13:12:34Z",
            isFork: false,
            isPrivate: false,
            isTemplate: false,
            isArchived: false,
            isEmpty: false,
            forkCount: 0,
            stargazerCount: 0,
            viewerCanUpdateTopics: true,
            viewerCanAdminister: true,
            repositoryTopics: {
              nodes: [
                {
                  id: "RT_kwDOHQu4Y84DQAl2",
                  resourcePath: "/topics/developer",
                  topic: {
                    id: "MDU6VG9waWNkZXZlbG9wZXI=",
                    name: "developer",
                  },
                  url: "https://github.com/topics/developer",
                },
                {
                  id: "RT_kwDOHQu4Y84DQAl3",
                  resourcePath: "/topics/react",
                  topic: {
                    id: "MDU6VG9waWNyZWFjdA==",
                    name: "react",
                  },
                  url: "https://github.com/topics/react",
                },
                {
                  id: "RT_kwDOHQu4Y84DQAl4",
                  resourcePath: "/topics/typescript",
                  topic: {
                    id: "MDU6VG9waWN0eXBlc2NyaXB0",
                    name: "typescript",
                  },
                  url: "https://github.com/topics/typescript",
                },
              ],
            },
          },
        },
        {
          cursor: "Y3Vyc29yOnYyOpHOHRDs0g==",
          node: {
            id: "R_kgDOHRDs0g",
            name: "portfolio",
            viewerPermission: "ADMIN",
            nameWithOwner: "tigawanna/portfolio",
            description: null,
            url: "https://github.com/tigawanna/portfolio",
            openGraphImageUrl:
              "https://opengraph.githubassets.com/b4949b759391d67193ba9b0ccf38232222ef528e5ff444ac922a7e53520b05b0/tigawanna/portfolio",
            updatedAt: "2022-05-01T21:42:25Z",
            isFork: false,
            isPrivate: false,
            isTemplate: false,
            isArchived: false,
            isEmpty: false,
            forkCount: 0,
            stargazerCount: 0,
            viewerCanUpdateTopics: true,
            viewerCanAdminister: true,
            repositoryTopics: {
              nodes: [],
            },
          },
        },
        {
          cursor: "Y3Vyc29yOnYyOpHOHSVCcw==",
          node: {
            id: "R_kgDOHSVCcw",
            name: "simple_shell",
            viewerPermission: "ADMIN",
            nameWithOwner: "tigawanna/simple_shell",
            description: "diy linux shell",
            url: "https://github.com/tigawanna/simple_shell",
            openGraphImageUrl:
              "https://opengraph.githubassets.com/df54b8a6ab6ab6537f44527d9e13b3e7ee3c63a6741701ad9cb2f2769a09dce7/tigawanna/simple_shell",
            updatedAt: "2022-05-06T18:05:05Z",
            isFork: false,
            isPrivate: false,
            isTemplate: false,
            isArchived: false,
            isEmpty: false,
            forkCount: 1,
            stargazerCount: 0,
            viewerCanUpdateTopics: true,
            viewerCanAdminister: true,
            repositoryTopics: {
              nodes: [],
            },
          },
        },
        {
          cursor: "Y3Vyc29yOnYyOpHOHTLynQ==",
          node: {
            id: "R_kgDOHTLynQ",
            name: "wsl-ubuntu-article",
            viewerPermission: "ADMIN",
            nameWithOwner: "tigawanna/wsl-ubuntu-article",
            description: null,
            url: "https://github.com/tigawanna/wsl-ubuntu-article",
            openGraphImageUrl:
              "https://opengraph.githubassets.com/f49a8872bd141386c2355fc13c427a56a04e1d55b64a33d09f85cd2f33933600/tigawanna/wsl-ubuntu-article",
            updatedAt: "2022-05-08T07:41:58Z",
            isFork: false,
            isPrivate: false,
            isTemplate: false,
            isArchived: false,
            isEmpty: false,
            forkCount: 0,
            stargazerCount: 0,
            viewerCanUpdateTopics: true,
            viewerCanAdminister: true,
            repositoryTopics: {
              nodes: [],
            },
          },
        },
        {
          cursor: "Y3Vyc29yOnYyOpHOHTiNpg==",
          node: {
            id: "R_kgDOHTiNpg",
            name: "agrho",
            viewerPermission: "ADMIN",
            nameWithOwner: "tigawanna/agrho",
            description: null,
            url: "https://github.com/tigawanna/agrho",
            openGraphImageUrl:
              "https://avatars.githubusercontent.com/u/72096712?s=400&v=4",
            updatedAt: "2022-07-01T21:15:28Z",
            isFork: false,
            isPrivate: true,
            isTemplate: false,
            isArchived: false,
            isEmpty: false,
            forkCount: 0,
            stargazerCount: 0,
            viewerCanUpdateTopics: true,
            viewerCanAdminister: true,
            repositoryTopics: {
              nodes: [],
            },
          },
        },
        {
          cursor: "Y3Vyc29yOnYyOpHOHXNwtQ==",
          node: {
            id: "R_kgDOHXNwtQ",
            name: "starter-files-for-project-manager",
            viewerPermission: "ADMIN",
            nameWithOwner: "tigawanna/starter-files-for-project-manager",
            description: null,
            url: "https://github.com/tigawanna/starter-files-for-project-manager",
            openGraphImageUrl:
              "https://opengraph.githubassets.com/9c228a98da8d33e24d565083bd8317eae4f2b72eda083273cc2f9ee05f839c9f/tigawanna/starter-files-for-project-manager",
            updatedAt: "2022-05-19T14:24:43Z",
            isFork: false,
            isPrivate: false,
            isTemplate: false,
            isArchived: false,
            isEmpty: false,
            forkCount: 0,
            stargazerCount: 0,
            viewerCanUpdateTopics: true,
            viewerCanAdminister: true,
            repositoryTopics: {
              nodes: [],
            },
          },
        },
        {
          cursor: "Y3Vyc29yOnYyOpHOHXjW4A==",
          node: {
            id: "R_kgDOHXjW4A",
            name: "project-mangaer",
            viewerPermission: "ADMIN",
            nameWithOwner: "tigawanna/project-mangaer",
            description: null,
            url: "https://github.com/tigawanna/project-mangaer",
            openGraphImageUrl:
              "https://opengraph.githubassets.com/1c37e6299b508f9d779f1639def65ed0109df883c7647f33de58f38383af3ef4/tigawanna/project-mangaer",
            updatedAt: "2022-09-22T07:32:36Z",
            isFork: false,
            isPrivate: false,
            isTemplate: false,
            isArchived: false,
            isEmpty: false,
            forkCount: 0,
            stargazerCount: 1,
            viewerCanUpdateTopics: true,
            viewerCanAdminister: true,
            repositoryTopics: {
              nodes: [],
            },
          },
        },
        {
          cursor: "Y3Vyc29yOnYyOpHOHYjPIQ==",
          node: {
            id: "R_kgDOHYjPIQ",
            name: "node-server-template",
            viewerPermission: "ADMIN",
            nameWithOwner: "tigawanna/node-server-template",
            description: null,
            url: "https://github.com/tigawanna/node-server-template",
            openGraphImageUrl:
              "https://opengraph.githubassets.com/cdb7a234decbb24f66cc8b1f57cd71fd076d1b045c058ad8c7460867bfa0ee18/tigawanna/node-server-template",
            updatedAt: "2022-04-30T13:34:20Z",
            isFork: true,
            isPrivate: false,
            isTemplate: false,
            isArchived: false,
            isEmpty: false,
            forkCount: 0,
            stargazerCount: 0,
            viewerCanUpdateTopics: true,
            viewerCanAdminister: true,
            repositoryTopics: {
              nodes: [],
            },
          },
        },
        {
          cursor: "Y3Vyc29yOnYyOpHOHaP3xQ==",
          node: {
            id: "R_kgDOHaP3xQ",
            name: "google-api-auth",
            viewerPermission: "ADMIN",
            nameWithOwner: "tigawanna/google-api-auth",
            description: null,
            url: "https://github.com/tigawanna/google-api-auth",
            openGraphImageUrl:
              "https://opengraph.githubassets.com/a0b8c14994873979099130b2588a461e1709a01fecdaff1df9018bec286b3197/tigawanna/google-api-auth",
            updatedAt: "2022-05-28T10:28:27Z",
            isFork: false,
            isPrivate: false,
            isTemplate: false,
            isArchived: false,
            isEmpty: false,
            forkCount: 0,
            stargazerCount: 0,
            viewerCanUpdateTopics: true,
            viewerCanAdminister: true,
            repositoryTopics: {
              nodes: [],
            },
          },
        },
        {
          cursor: "Y3Vyc29yOnYyOpHOHa8rkw==",
          node: {
            id: "R_kgDOHa8rkw",
            name: "alx-higher_level_programming",
            viewerPermission: "ADMIN",
            nameWithOwner: "tigawanna/alx-higher_level_programming",
            description:
              "repository fro higer level programming languges for the alx softwarae engineering program",
            url: "https://github.com/tigawanna/alx-higher_level_programming",
            openGraphImageUrl:
              "https://opengraph.githubassets.com/ab7cc7647cd4a5f9d3cfd8b3c2924846374429e2a1b65a698020c9cf9ef0f9b6/tigawanna/alx-higher_level_programming",
            updatedAt: "2022-05-31T08:28:35Z",
            isFork: false,
            isPrivate: false,
            isTemplate: false,
            isArchived: false,
            isEmpty: false,
            forkCount: 4,
            stargazerCount: 0,
            viewerCanUpdateTopics: true,
            viewerCanAdminister: true,
            repositoryTopics: {
              nodes: [],
            },
          },
        },
        {
          cursor: "Y3Vyc29yOnYyOpHOHbOCaQ==",
          node: {
            id: "R_kgDOHbOCaQ",
            name: "API-myGoalsApp",
            viewerPermission: "ADMIN",
            nameWithOwner: "tigawanna/API-myGoalsApp",
            description:
              "This repository contains a simple api for goals application whereby you can create, update, read and delete your goals. The data is stored into a MongoDb database. The app is created in an iconic and adorable UI & UX design using REACT and data managed in an amazing way using NODE.",
            url: "https://github.com/tigawanna/API-myGoalsApp",
            openGraphImageUrl:
              "https://opengraph.githubassets.com/e89485d33a3b421230abaa4e1988011460248f20dfce0134bead789727a87192/tigawanna/API-myGoalsApp",
            updatedAt: "2022-05-31T14:03:50Z",
            isFork: true,
            isPrivate: false,
            isTemplate: false,
            isArchived: false,
            isEmpty: false,
            forkCount: 0,
            stargazerCount: 1,
            viewerCanUpdateTopics: true,
            viewerCanAdminister: true,
            repositoryTopics: {
              nodes: [],
            },
          },
        },
        {
          cursor: "Y3Vyc29yOnYyOpHOHcuMGg==",
          node: {
            id: "R_kgDOHcuMGg",
            name: "node-express-typescript",
            viewerPermission: "ADMIN",
            nameWithOwner: "tigawanna/node-express-typescript",
            description: null,
            url: "https://github.com/tigawanna/node-express-typescript",
            openGraphImageUrl:
              "https://opengraph.githubassets.com/19a8d84e9b1d33cf676dc5810f97d6abc7627b87e8eb4d478bbea6f9f6780477/tigawanna/node-express-typescript",
            updatedAt: "2022-06-04T16:27:23Z",
            isFork: false,
            isPrivate: false,
            isTemplate: false,
            isArchived: false,
            isEmpty: false,
            forkCount: 0,
            stargazerCount: 0,
            viewerCanUpdateTopics: true,
            viewerCanAdminister: true,
            repositoryTopics: {
              nodes: [],
            },
          },
        },
        {
          cursor: "Y3Vyc29yOnYyOpHOHcuh8w==",
          node: {
            id: "R_kgDOHcuh8w",
            name: "google-api-server",
            viewerPermission: "ADMIN",
            nameWithOwner: "tigawanna/google-api-server",
            description: null,
            url: "https://github.com/tigawanna/google-api-server",
            openGraphImageUrl:
              "https://opengraph.githubassets.com/d47dded0c06ed042ce0ddb4fda7f138fd224e8fda452b1b931987a8a316ae4f6/tigawanna/google-api-server",
            updatedAt: "2022-06-04T16:50:22Z",
            isFork: false,
            isPrivate: false,
            isTemplate: false,
            isArchived: false,
            isEmpty: false,
            forkCount: 0,
            stargazerCount: 0,
            viewerCanUpdateTopics: true,
            viewerCanAdminister: true,
            repositoryTopics: {
              nodes: [],
            },
          },
        },
        {
          cursor: "Y3Vyc29yOnYyOpHOHfDI3g==",
          node: {
            id: "R_kgDOHfDI3g",
            name: "Weather-App",
            viewerPermission: "ADMIN",
            nameWithOwner: "tigawanna/Weather-App",
            description: null,
            url: "https://github.com/tigawanna/Weather-App",
            openGraphImageUrl:
              "https://opengraph.githubassets.com/ef20293b936185be633dd303fad9a3439feeeff058c37187c3475348af414996/tigawanna/Weather-App",
            updatedAt: "2022-06-11T17:37:16Z",
            isFork: true,
            isPrivate: false,
            isTemplate: false,
            isArchived: false,
            isEmpty: false,
            forkCount: 0,
            stargazerCount: 0,
            viewerCanUpdateTopics: true,
            viewerCanAdminister: true,
            repositoryTopics: {
              nodes: [],
            },
          },
        },
        {
          cursor: "Y3Vyc29yOnYyOpHOHgESyw==",
          node: {
            id: "R_kgDOHgESyw",
            name: "monty",
            viewerPermission: "ADMIN",
            nameWithOwner: "tigawanna/monty",
            description: "c stack and heap",
            url: "https://github.com/tigawanna/monty",
            openGraphImageUrl:
              "https://opengraph.githubassets.com/fc3214423da372bbc5b0ecd9488411a3eec3070f102422366c90891148449968/tigawanna/monty",
            updatedAt: "2022-06-16T09:33:46Z",
            isFork: false,
            isPrivate: false,
            isTemplate: false,
            isArchived: false,
            isEmpty: false,
            forkCount: 1,
            stargazerCount: 0,
            viewerCanUpdateTopics: true,
            viewerCanAdminister: true,
            repositoryTopics: {
              nodes: [],
            },
          },
        },
        {
          cursor: "Y3Vyc29yOnYyOpHOHhv6-Q==",
          node: {
            id: "R_kgDOHhv6-Q",
            name: "code-cademy",
            viewerPermission: "ADMIN",
            nameWithOwner: "tigawanna/code-cademy",
            description: null,
            url: "https://github.com/tigawanna/code-cademy",
            openGraphImageUrl:
              "https://opengraph.githubassets.com/99b4c5da185e1613cf6506815da23fb380046e72d49f2b2a81e3eb3163b829cb/tigawanna/code-cademy",
            updatedAt: "2022-06-19T15:41:05Z",
            isFork: false,
            isPrivate: false,
            isTemplate: false,
            isArchived: false,
            isEmpty: false,
            forkCount: 0,
            stargazerCount: 0,
            viewerCanUpdateTopics: true,
            viewerCanAdminister: true,
            repositoryTopics: {
              nodes: [],
            },
          },
        },
        {
          cursor: "Y3Vyc29yOnYyOpHOHljBew==",
          node: {
            id: "R_kgDOHljBew",
            name: "c-practice",
            viewerPermission: "ADMIN",
            nameWithOwner: "tigawanna/c-practice",
            description: null,
            url: "https://github.com/tigawanna/c-practice",
            openGraphImageUrl:
              "https://opengraph.githubassets.com/a41be044108f6349eb61f26cc5040d848f6c72d46e53a45d971d10f73caa4c78/tigawanna/c-practice",
            updatedAt: "2022-06-30T15:24:03Z",
            isFork: false,
            isPrivate: false,
            isTemplate: false,
            isArchived: false,
            isEmpty: false,
            forkCount: 0,
            stargazerCount: 0,
            viewerCanUpdateTopics: true,
            viewerCanAdminister: true,
            repositoryTopics: {
              nodes: [],
            },
          },
        },
        {
          cursor: "Y3Vyc29yOnYyOpHOHmk8Uw==",
          node: {
            id: "R_kgDOHmk8Uw",
            name: "table-for-react",
            viewerPermission: "ADMIN",
            nameWithOwner: "tigawanna/table-for-react",
            description: null,
            url: "https://github.com/tigawanna/table-for-react",
            openGraphImageUrl:
              "https://opengraph.githubassets.com/0f2d7b4a547f6ffc6d7094620b4680e8a65ba7ea592a3e6bd2461e426ff9559a/tigawanna/table-for-react",
            updatedAt: "2022-07-04T04:38:28Z",
            isFork: false,
            isPrivate: false,
            isTemplate: false,
            isArchived: false,
            isEmpty: false,
            forkCount: 0,
            stargazerCount: 0,
            viewerCanUpdateTopics: true,
            viewerCanAdminister: true,
            repositoryTopics: {
              nodes: [],
            },
          },
        },
        {
          cursor: "Y3Vyc29yOnYyOpHOHmsTZw==",
          node: {
            id: "R_kgDOHmsTZw",
            name: "pitch",
            viewerPermission: "ADMIN",
            nameWithOwner: "tigawanna/pitch",
            description:
              "A flask application to write,view and comment on different pitches",
            url: "https://github.com/tigawanna/pitch",
            openGraphImageUrl:
              "https://opengraph.githubassets.com/448ce54a775598fcbb3fbf2f98c284216315634c934e7858dcdfe47134137df7/tigawanna/pitch",
            updatedAt: "2018-02-09T01:58:11Z",
            isFork: true,
            isPrivate: false,
            isTemplate: false,
            isArchived: false,
            isEmpty: false,
            forkCount: 0,
            stargazerCount: 0,
            viewerCanUpdateTopics: true,
            viewerCanAdminister: true,
            repositoryTopics: {
              nodes: [],
            },
          },
        },
        {
          cursor: "Y3Vyc29yOnYyOpHOHmvLZg==",
          node: {
            id: "R_kgDOHmvLZg",
            name: "table-for-react-example",
            viewerPermission: "ADMIN",
            nameWithOwner: "tigawanna/table-for-react-example",
            description: null,
            url: "https://github.com/tigawanna/table-for-react-example",
            openGraphImageUrl:
              "https://opengraph.githubassets.com/90d5f5f964a93a5304f6abdbc46d4c32d76f74f6cae3ff51fd1908b1931b14bb/tigawanna/table-for-react-example",
            updatedAt: "2022-07-04T14:00:38Z",
            isFork: false,
            isPrivate: false,
            isTemplate: false,
            isArchived: false,
            isEmpty: false,
            forkCount: 0,
            stargazerCount: 0,
            viewerCanUpdateTopics: true,
            viewerCanAdminister: true,
            repositoryTopics: {
              nodes: [],
            },
          },
        },
        {
          cursor: "Y3Vyc29yOnYyOpHOHosSiw==",
          node: {
            id: "R_kgDOHosSiw",
            name: "projects",
            viewerPermission: "ADMIN",
            nameWithOwner: "tigawanna/projects",
            description: null,
            url: "https://github.com/tigawanna/projects",
            openGraphImageUrl:
              "https://opengraph.githubassets.com/ac30e0796deb177eef3e2647cbcaa631209b054af4b6f24a1ea4c56a2739ac65/tigawanna/projects",
            updatedAt: "2022-07-10T12:36:08Z",
            isFork: false,
            isPrivate: false,
            isTemplate: false,
            isArchived: false,
            isEmpty: false,
            forkCount: 0,
            stargazerCount: 0,
            viewerCanUpdateTopics: true,
            viewerCanAdminister: true,
            repositoryTopics: {
              nodes: [],
            },
          },
        },
        {
          cursor: "Y3Vyc29yOnYyOpHOHpJ1pQ==",
          node: {
            id: "R_kgDOHpJ1pQ",
            name: "chat-client",
            viewerPermission: "ADMIN",
            nameWithOwner: "tigawanna/chat-client",
            description: null,
            url: "https://github.com/tigawanna/chat-client",
            openGraphImageUrl:
              "https://opengraph.githubassets.com/d5f22b37fd7b011dedfc37deaadbb888ac03d7dd3b3abb67dc66434d62fa3ce9/tigawanna/chat-client",
            updatedAt: "2022-07-11T21:34:47Z",
            isFork: false,
            isPrivate: false,
            isTemplate: false,
            isArchived: false,
            isEmpty: false,
            forkCount: 0,
            stargazerCount: 0,
            viewerCanUpdateTopics: true,
            viewerCanAdminister: true,
            repositoryTopics: {
              nodes: [],
            },
          },
        },
        {
          cursor: "Y3Vyc29yOnYyOpHOHpKFAw==",
          node: {
            id: "R_kgDOHpKFAw",
            name: "chat-server",
            viewerPermission: "ADMIN",
            nameWithOwner: "tigawanna/chat-server",
            description: null,
            url: "https://github.com/tigawanna/chat-server",
            openGraphImageUrl:
              "https://opengraph.githubassets.com/7c7f5a882f2f24f48d408a6a5bc5cd6e3a66a0004ee8536bd5b52d610c13baea/tigawanna/chat-server",
            updatedAt: "2022-07-11T21:53:32Z",
            isFork: false,
            isPrivate: false,
            isTemplate: false,
            isArchived: false,
            isEmpty: false,
            forkCount: 0,
            stargazerCount: 0,
            viewerCanUpdateTopics: true,
            viewerCanAdminister: true,
            repositoryTopics: {
              nodes: [],
            },
          },
        },
        {
          cursor: "Y3Vyc29yOnYyOpHOHpLYYA==",
          node: {
            id: "R_kgDOHpLYYA",
            name: "bills-nodejs",
            viewerPermission: "ADMIN",
            nameWithOwner: "tigawanna/bills-nodejs",
            description: null,
            url: "https://github.com/tigawanna/bills-nodejs",
            openGraphImageUrl:
              "https://opengraph.githubassets.com/5798222061244642229cf4d2b254ca2f5354d216b666d7934034403c1ca1b1f1/tigawanna/bills-nodejs",
            updatedAt: "2022-04-30T13:24:52Z",
            isFork: true,
            isPrivate: false,
            isTemplate: false,
            isArchived: false,
            isEmpty: false,
            forkCount: 0,
            stargazerCount: 0,
            viewerCanUpdateTopics: true,
            viewerCanAdminister: true,
            repositoryTopics: {
              nodes: [],
            },
          },
        },
        {
          cursor: "Y3Vyc29yOnYyOpHOHpgycw==",
          node: {
            id: "R_kgDOHpgycw",
            name: "sockets-server",
            viewerPermission: "ADMIN",
            nameWithOwner: "tigawanna/sockets-server",
            description: null,
            url: "https://github.com/tigawanna/sockets-server",
            openGraphImageUrl:
              "https://opengraph.githubassets.com/4e347b3363dc92432ce4a7808ae60b0a171fc4b9fff435ea64568f1e5c479cd7/tigawanna/sockets-server",
            updatedAt: "2022-11-17T14:38:15Z",
            isFork: false,
            isPrivate: false,
            isTemplate: false,
            isArchived: false,
            isEmpty: false,
            forkCount: 0,
            stargazerCount: 1,
            viewerCanUpdateTopics: true,
            viewerCanAdminister: true,
            repositoryTopics: {
              nodes: [],
            },
          },
        },
        {
          cursor: "Y3Vyc29yOnYyOpHOHpg8lg==",
          node: {
            id: "R_kgDOHpg8lg",
            name: "sockets-client",
            viewerPermission: "ADMIN",
            nameWithOwner: "tigawanna/sockets-client",
            description: null,
            url: "https://github.com/tigawanna/sockets-client",
            openGraphImageUrl:
              "https://opengraph.githubassets.com/e6cbcc107f265455a30da4c36ce6b87f45f79b0c7965eb9c6192eb478aa1fe5b/tigawanna/sockets-client",
            updatedAt: "2022-11-17T14:38:12Z",
            isFork: false,
            isPrivate: false,
            isTemplate: false,
            isArchived: false,
            isEmpty: false,
            forkCount: 0,
            stargazerCount: 1,
            viewerCanUpdateTopics: true,
            viewerCanAdminister: true,
            repositoryTopics: {
              nodes: [],
            },
          },
        },
        {
          cursor: "Y3Vyc29yOnYyOpHOHqHXzQ==",
          node: {
            id: "R_kgDOHqHXzQ",
            name: "sorting_algorithms",
            viewerPermission: "ADMIN",
            nameWithOwner: "tigawanna/sorting_algorithms",
            description: null,
            url: "https://github.com/tigawanna/sorting_algorithms",
            openGraphImageUrl:
              "https://opengraph.githubassets.com/c8cc505d6835114df334bc2dfa70df0c0374065016d30aa97e144c9cd323f4f5/tigawanna/sorting_algorithms",
            updatedAt: "2022-07-14T22:26:29Z",
            isFork: false,
            isPrivate: false,
            isTemplate: false,
            isArchived: false,
            isEmpty: false,
            forkCount: 0,
            stargazerCount: 0,
            viewerCanUpdateTopics: true,
            viewerCanAdminister: true,
            repositoryTopics: {
              nodes: [],
            },
          },
        },
        {
          cursor: "Y3Vyc29yOnYyOpHOHrdZ9Q==",
          node: {
            id: "R_kgDOHrdZ9Q",
            name: "sockets-rn",
            viewerPermission: "ADMIN",
            nameWithOwner: "tigawanna/sockets-rn",
            description: null,
            url: "https://github.com/tigawanna/sockets-rn",
            openGraphImageUrl:
              "https://opengraph.githubassets.com/42349924eb6fa42d232f96b04cb15089dd2579dd8ada139c82ecbeae832078b6/tigawanna/sockets-rn",
            updatedAt: "2022-11-17T14:38:19Z",
            isFork: false,
            isPrivate: false,
            isTemplate: false,
            isArchived: false,
            isEmpty: false,
            forkCount: 0,
            stargazerCount: 1,
            viewerCanUpdateTopics: true,
            viewerCanAdminister: true,
            repositoryTopics: {
              nodes: [],
            },
          },
        },
        {
          cursor: "Y3Vyc29yOnYyOpHOHtLIIw==",
          node: {
            id: "R_kgDOHtLIIw",
            name: "basic-express-nodejs",
            viewerPermission: "ADMIN",
            nameWithOwner: "tigawanna/basic-express-nodejs",
            description: null,
            url: "https://github.com/tigawanna/basic-express-nodejs",
            openGraphImageUrl:
              "https://opengraph.githubassets.com/14d276ea17a5664a487a8dffd20387b9ba81a716a52437c3be16a87a6f33ecc1/tigawanna/basic-express-nodejs",
            updatedAt: "2022-07-23T18:08:38Z",
            isFork: false,
            isPrivate: false,
            isTemplate: false,
            isArchived: false,
            isEmpty: false,
            forkCount: 0,
            stargazerCount: 0,
            viewerCanUpdateTopics: true,
            viewerCanAdminister: true,
            repositoryTopics: {
              nodes: [],
            },
          },
        },
        {
          cursor: "Y3Vyc29yOnYyOpHOHtb0tg==",
          node: {
            id: "R_kgDOHtb0tg",
            name: "gitpals",
            viewerPermission: "ADMIN",
            nameWithOwner: "tigawanna/gitpals",
            description: null,
            url: "https://github.com/tigawanna/gitpals",
            openGraphImageUrl:
              "https://opengraph.githubassets.com/82c4d96074af300014828c331535e6afa031cb4cb89284a3e0ca164925f50d71/tigawanna/gitpals",
            updatedAt: "2022-08-23T04:14:53Z",
            isFork: false,
            isPrivate: false,
            isTemplate: false,
            isArchived: false,
            isEmpty: false,
            forkCount: 1,
            stargazerCount: 1,
            viewerCanUpdateTopics: true,
            viewerCanAdminister: true,
            repositoryTopics: {
              nodes: [],
            },
          },
        },
        {
          cursor: "Y3Vyc29yOnYyOpHOHtuJpg==",
          node: {
            id: "R_kgDOHtuJpg",
            name: "clinic_api",
            viewerPermission: "ADMIN",
            nameWithOwner: "tigawanna/clinic_api",
            description: "Node Ja clinic api",
            url: "https://github.com/tigawanna/clinic_api",
            openGraphImageUrl:
              "https://opengraph.githubassets.com/2c3db03776c82358690c77d56aa6057d7fd091c3e1a9854eceb07af25bba79ce/tigawanna/clinic_api",
            updatedAt: "2022-04-27T16:35:55Z",
            isFork: true,
            isPrivate: false,
            isTemplate: false,
            isArchived: false,
            isEmpty: false,
            forkCount: 0,
            stargazerCount: 0,
            viewerCanUpdateTopics: true,
            viewerCanAdminister: true,
            repositoryTopics: {
              nodes: [],
            },
          },
        },
        {
          cursor: "Y3Vyc29yOnYyOpHOHtuMxQ==",
          node: {
            id: "R_kgDOHtuMxQ",
            name: "clinic_app",
            viewerPermission: "ADMIN",
            nameWithOwner: "tigawanna/clinic_app",
            description: "Clinic app client ",
            url: "https://github.com/tigawanna/clinic_app",
            openGraphImageUrl:
              "https://opengraph.githubassets.com/ffab2927a33612d4557edcbec359e6bd31a55cd4f0398ca106f58f74287b9fa1/tigawanna/clinic_app",
            updatedAt: "2022-04-27T16:34:58Z",
            isFork: true,
            isPrivate: false,
            isTemplate: false,
            isArchived: false,
            isEmpty: false,
            forkCount: 0,
            stargazerCount: 0,
            viewerCanUpdateTopics: true,
            viewerCanAdminister: true,
            repositoryTopics: {
              nodes: [],
            },
          },
        },
        {
          cursor: "Y3Vyc29yOnYyOpHOHuInww==",
          node: {
            id: "R_kgDOHuInww",
            name: "algospractice",
            viewerPermission: "ADMIN",
            nameWithOwner: "tigawanna/algospractice",
            description: null,
            url: "https://github.com/tigawanna/algospractice",
            openGraphImageUrl:
              "https://opengraph.githubassets.com/b92a23e34929a2e4ef01144614af7c5d5b5bf31715f73be25261f44df1fbde6f/tigawanna/algospractice",
            updatedAt: "2022-07-26T16:29:43Z",
            isFork: false,
            isPrivate: false,
            isTemplate: false,
            isArchived: false,
            isEmpty: false,
            forkCount: 0,
            stargazerCount: 0,
            viewerCanUpdateTopics: true,
            viewerCanAdminister: true,
            repositoryTopics: {
              nodes: [],
            },
          },
        },
        {
          cursor: "Y3Vyc29yOnYyOpHOHvZljw==",
          node: {
            id: "R_kgDOHvZljw",
            name: "learning-flask",
            viewerPermission: "ADMIN",
            nameWithOwner: "tigawanna/learning-flask",
            description: null,
            url: "https://github.com/tigawanna/learning-flask",
            openGraphImageUrl:
              "https://opengraph.githubassets.com/65b45d7f680252d2d6cd645ad5c759f86cbb8fc0447370648110cd212702d04c/tigawanna/learning-flask",
            updatedAt: "2022-07-30T09:05:54Z",
            isFork: false,
            isPrivate: false,
            isTemplate: false,
            isArchived: false,
            isEmpty: false,
            forkCount: 0,
            stargazerCount: 0,
            viewerCanUpdateTopics: true,
            viewerCanAdminister: true,
            repositoryTopics: {
              nodes: [],
            },
          },
        },
        {
          cursor: "Y3Vyc29yOnYyOpHOHv8OZw==",
          node: {
            id: "R_kgDOHv8OZw",
            name: "AirBnB_clone",
            viewerPermission: "WRITE",
            nameWithOwner: "chrpkorir/AirBnB_clone",
            description: null,
            url: "https://github.com/chrpkorir/AirBnB_clone",
            openGraphImageUrl:
              "https://opengraph.githubassets.com/18d2e975baa250a9c3c27b729bd5ee01037b07d9af12f6c81a8535090eb686e6/chrpkorir/AirBnB_clone",
            updatedAt: "2022-08-11T12:27:27Z",
            isFork: false,
            isPrivate: false,
            isTemplate: false,
            isArchived: false,
            isEmpty: false,
            forkCount: 1,
            stargazerCount: 1,
            viewerCanUpdateTopics: false,
            viewerCanAdminister: false,
            repositoryTopics: {
              nodes: [],
            },
          },
        },
        {
          cursor: "Y3Vyc29yOnYyOpHOHzZ4DA==",
          node: {
            id: "R_kgDOHzZ4DA",
            name: "AirBnB_clone",
            viewerPermission: "ADMIN",
            nameWithOwner: "tigawanna/AirBnB_clone",
            description: "My copy of the Airbnb clone project ",
            url: "https://github.com/tigawanna/AirBnB_clone",
            openGraphImageUrl:
              "https://opengraph.githubassets.com/b8b894402691eb1e5cb86c6841694adac16601dbe2ec2384cdb62ec869eda878/tigawanna/AirBnB_clone",
            updatedAt: "2022-08-11T12:29:21Z",
            isFork: true,
            isPrivate: false,
            isTemplate: false,
            isArchived: false,
            isEmpty: false,
            forkCount: 0,
            stargazerCount: 0,
            viewerCanUpdateTopics: true,
            viewerCanAdminister: true,
            repositoryTopics: {
              nodes: [],
            },
          },
        },
        {
          cursor: "Y3Vyc29yOnYyOpHOHzt-Dw==",
          node: {
            id: "R_kgDOHzt-Dw",
            name: "Fix_My_Code_Challenge",
            viewerPermission: "ADMIN",
            nameWithOwner: "tigawanna/Fix_My_Code_Challenge",
            description: null,
            url: "https://github.com/tigawanna/Fix_My_Code_Challenge",
            openGraphImageUrl:
              "https://opengraph.githubassets.com/c522447d69ec954f74e54c798ce3d259ce7bdf5aaba9df71955376ccfd822fd2/tigawanna/Fix_My_Code_Challenge",
            updatedAt: "2022-08-12T07:19:07Z",
            isFork: false,
            isPrivate: false,
            isTemplate: false,
            isArchived: false,
            isEmpty: false,
            forkCount: 0,
            stargazerCount: 0,
            viewerCanUpdateTopics: true,
            viewerCanAdminister: true,
            repositoryTopics: {
              nodes: [],
            },
          },
        },
        {
          cursor: "Y3Vyc29yOnYyOpHOH3Hujg==",
          node: {
            id: "R_kgDOH3Hujg",
            name: "binary_trees",
            viewerPermission: "ADMIN",
            nameWithOwner: "tigawanna/binary_trees",
            description: null,
            url: "https://github.com/tigawanna/binary_trees",
            openGraphImageUrl:
              "https://opengraph.githubassets.com/d9b91169ba588c55bac52d966887ede258de5948ed30b3cb49140f7d00109655/tigawanna/binary_trees",
            updatedAt: "2022-08-24T02:23:13Z",
            isFork: false,
            isPrivate: false,
            isTemplate: false,
            isArchived: false,
            isEmpty: false,
            forkCount: 0,
            stargazerCount: 0,
            viewerCanUpdateTopics: true,
            viewerCanAdminister: true,
            repositoryTopics: {
              nodes: [],
            },
          },
        },
        {
          cursor: "Y3Vyc29yOnYyOpHOH5Gmvg==",
          node: {
            id: "R_kgDOH5Gmvg",
            name: "gitcircles",
            viewerPermission: "ADMIN",
            nameWithOwner: "tigawanna/gitcircles",
            description: null,
            url: "https://github.com/tigawanna/gitcircles",
            openGraphImageUrl:
              "https://opengraph.githubassets.com/e0e85912a5b7fedc9c71a0d151c618b8d018abbfb102eb9809d8d2be2b16b113/tigawanna/gitcircles",
            updatedAt: "2022-08-27T16:31:31Z",
            isFork: false,
            isPrivate: false,
            isTemplate: false,
            isArchived: false,
            isEmpty: false,
            forkCount: 0,
            stargazerCount: 0,
            viewerCanUpdateTopics: true,
            viewerCanAdminister: true,
            repositoryTopics: {
              nodes: [],
            },
          },
        },
        {
          cursor: "Y3Vyc29yOnYyOpHOH5qgog==",
          node: {
            id: "R_kgDOH5qgog",
            name: "gitdeck",
            viewerPermission: "ADMIN",
            nameWithOwner: "tigawanna/gitdeck",
            description: null,
            url: "https://github.com/tigawanna/gitdeck",
            openGraphImageUrl:
              "https://opengraph.githubassets.com/c937f48a75f975870f1a607126b34d0b3124d94c495effd00c1ab812155b2094/tigawanna/gitdeck",
            updatedAt: "2022-11-17T14:20:46Z",
            isFork: false,
            isPrivate: false,
            isTemplate: false,
            isArchived: false,
            isEmpty: false,
            forkCount: 0,
            stargazerCount: 1,
            viewerCanUpdateTopics: true,
            viewerCanAdminister: true,
            repositoryTopics: {
              nodes: [],
            },
          },
        },
        {
          cursor: "Y3Vyc29yOnYyOpHOH77ZAQ==",
          node: {
            id: "R_kgDOH77ZAQ",
            name: "first-golang",
            viewerPermission: "ADMIN",
            nameWithOwner: "tigawanna/first-golang",
            description: null,
            url: "https://github.com/tigawanna/first-golang",
            openGraphImageUrl:
              "https://opengraph.githubassets.com/83241ef1a3ce9b331d88ffe59ecf5c7864b1c1bd97e8fb4caa9a905bf589be89/tigawanna/first-golang",
            updatedAt: "2022-09-04T16:54:43Z",
            isFork: false,
            isPrivate: false,
            isTemplate: false,
            isArchived: false,
            isEmpty: false,
            forkCount: 0,
            stargazerCount: 0,
            viewerCanUpdateTopics: true,
            viewerCanAdminister: true,
            repositoryTopics: {
              nodes: [],
            },
          },
        },
        {
          cursor: "Y3Vyc29yOnYyOpHOH8Vn-Q==",
          node: {
            id: "R_kgDOH8Vn-Q",
            name: "project-manager",
            viewerPermission: "ADMIN",
            nameWithOwner: "tigawanna/project-manager",
            description: null,
            url: "https://github.com/tigawanna/project-manager",
            openGraphImageUrl:
              "https://opengraph.githubassets.com/c46e7da789bd8b4402bd4b185d4648c51198a0f2d1ea3e50b7dfbeb25e10fb82/tigawanna/project-manager",
            updatedAt: "2022-09-07T10:14:53Z",
            isFork: false,
            isPrivate: false,
            isTemplate: false,
            isArchived: false,
            isEmpty: false,
            forkCount: 0,
            stargazerCount: 0,
            viewerCanUpdateTopics: true,
            viewerCanAdminister: true,
            repositoryTopics: {
              nodes: [],
            },
          },
        },
        {
          cursor: "Y3Vyc29yOnYyOpHOH8t79w==",
          node: {
            id: "R_kgDOH8t79w",
            name: "react-playground",
            viewerPermission: "ADMIN",
            nameWithOwner: "tigawanna/react-playground",
            description: null,
            url: "https://github.com/tigawanna/react-playground",
            openGraphImageUrl:
              "https://opengraph.githubassets.com/2e6dcb646894d5a76a0c26f173bd2d961c8a764e6a46d70fcf07253db420de45/tigawanna/react-playground",
            updatedAt: "2022-09-06T17:19:50Z",
            isFork: false,
            isPrivate: false,
            isTemplate: false,
            isArchived: false,
            isEmpty: false,
            forkCount: 0,
            stargazerCount: 0,
            viewerCanUpdateTopics: true,
            viewerCanAdminister: true,
            repositoryTopics: {
              nodes: [],
            },
          },
        },
        {
          cursor: "Y3Vyc29yOnYyOpHOH9wdGA==",
          node: {
            id: "R_kgDOH9wdGA",
            name: "AirBnB_clone_v2",
            viewerPermission: "ADMIN",
            nameWithOwner: "tigawanna/AirBnB_clone_v2",
            description: "airbnb clone v2 , adding sql database",
            url: "https://github.com/tigawanna/AirBnB_clone_v2",
            openGraphImageUrl:
              "https://opengraph.githubassets.com/987efd784d476f5e9fe093c4fe1c34fdd707d2d541a72922c9c2df9d05292785/tigawanna/AirBnB_clone_v2",
            updatedAt: "2022-09-12T08:28:04Z",
            isFork: true,
            isPrivate: false,
            isTemplate: false,
            isArchived: false,
            isEmpty: false,
            forkCount: 1,
            stargazerCount: 0,
            viewerCanUpdateTopics: true,
            viewerCanAdminister: true,
            repositoryTopics: {
              nodes: [],
            },
          },
        },
        {
          cursor: "Y3Vyc29yOnYyOpHOH_jUYQ==",
          node: {
            id: "R_kgDOH_jUYQ",
            name: "my-pocketbase-fork",
            viewerPermission: "ADMIN",
            nameWithOwner: "tigawanna/my-pocketbase-fork",
            description: "Open Source realtime backend in 1 file , my fork",
            url: "https://github.com/tigawanna/my-pocketbase-fork",
            openGraphImageUrl:
              "https://opengraph.githubassets.com/a9020802ca3c592df0bcd10570720d357cf54859fb60b51d730f093124e3aac1/tigawanna/my-pocketbase-fork",
            updatedAt: "2022-11-12T16:33:11Z",
            isFork: true,
            isPrivate: false,
            isTemplate: false,
            isArchived: false,
            isEmpty: false,
            forkCount: 0,
            stargazerCount: 0,
            viewerCanUpdateTopics: true,
            viewerCanAdminister: true,
            repositoryTopics: {
              nodes: [],
            },
          },
        },
        {
          cursor: "Y3Vyc29yOnYyOpHOH_qLYg==",
          node: {
            id: "R_kgDOH_qLYg",
            name: "supabase",
            viewerPermission: "ADMIN",
            nameWithOwner: "tigawanna/supabase",
            description:
              "The open source Firebase alternative. Follow to stay updated about our public Beta.",
            url: "https://github.com/tigawanna/supabase",
            openGraphImageUrl:
              "https://opengraph.githubassets.com/6462b70f02ea8ed3eb3572c4f4c13ea516bba5eea90647d8215ef90c811f0789/tigawanna/supabase",
            updatedAt: "2022-09-14T09:50:52Z",
            isFork: true,
            isPrivate: false,
            isTemplate: false,
            isArchived: false,
            isEmpty: false,
            forkCount: 0,
            stargazerCount: 0,
            viewerCanUpdateTopics: true,
            viewerCanAdminister: true,
            repositoryTopics: {
              nodes: [],
            },
          },
        },
        {
          cursor: "Y3Vyc29yOnYyOpHOIBJfQg==",
          node: {
            id: "R_kgDOIBJfQg",
            name: "pocket-base-example",
            viewerPermission: "ADMIN",
            nameWithOwner: "tigawanna/pocket-base-example",
            description: null,
            url: "https://github.com/tigawanna/pocket-base-example",
            openGraphImageUrl:
              "https://opengraph.githubassets.com/ed060d35615571f96474221bf84f48bf7a8237999154762cb474b29d7e149ebd/tigawanna/pocket-base-example",
            updatedAt: "2022-11-02T21:52:32Z",
            isFork: false,
            isPrivate: false,
            isTemplate: false,
            isArchived: false,
            isEmpty: false,
            forkCount: 0,
            stargazerCount: 3,
            viewerCanUpdateTopics: true,
            viewerCanAdminister: true,
            repositoryTopics: {
              nodes: [],
            },
          },
        },
        {
          cursor: "Y3Vyc29yOnYyOpHOIE1EWQ==",
          node: {
            id: "R_kgDOIE1EWQ",
            name: "starter-vite-relay",
            viewerPermission: "ADMIN",
            nameWithOwner: "tigawanna/starter-vite-relay",
            description: null,
            url: "https://github.com/tigawanna/starter-vite-relay",
            openGraphImageUrl:
              "https://opengraph.githubassets.com/0ba230f3de15505ff4590b31c39a37b7657e2d25745009e890b8bbf62d385e10/tigawanna/starter-vite-relay",
            updatedAt: "2022-11-17T14:28:16Z",
            isFork: false,
            isPrivate: false,
            isTemplate: false,
            isArchived: false,
            isEmpty: false,
            forkCount: 0,
            stargazerCount: 1,
            viewerCanUpdateTopics: true,
            viewerCanAdminister: true,
            repositoryTopics: {
              nodes: [],
            },
          },
        },
        {
          cursor: "Y3Vyc29yOnYyOpHOIIalAw==",
          node: {
            id: "R_kgDOIIalAw",
            name: "awesome-pocketbase",
            viewerPermission: "ADMIN",
            nameWithOwner: "tigawanna/awesome-pocketbase",
            description: null,
            url: "https://github.com/tigawanna/awesome-pocketbase",
            openGraphImageUrl:
              "https://opengraph.githubassets.com/870c78875799802530a34953f82d37f0a4172db6ed871de71384dab5647c81d6/tigawanna/awesome-pocketbase",
            updatedAt: "2022-10-04T20:25:23Z",
            isFork: true,
            isPrivate: false,
            isTemplate: false,
            isArchived: false,
            isEmpty: false,
            forkCount: 0,
            stargazerCount: 0,
            viewerCanUpdateTopics: true,
            viewerCanAdminister: true,
            repositoryTopics: {
              nodes: [],
            },
          },
        },
        {
          cursor: "Y3Vyc29yOnYyOpHOIIbLWA==",
          node: {
            id: "R_kgDOIIbLWA",
            name: "marmot",
            viewerPermission: "ADMIN",
            nameWithOwner: "tigawanna/marmot",
            description: "A distributed SQLite replicator built on top of NATS",
            url: "https://github.com/tigawanna/marmot",
            openGraphImageUrl:
              "https://opengraph.githubassets.com/10d4111af0bc8057f1c2fb78d614ca45ec237db49467f4b3e21a36762df468bd/tigawanna/marmot",
            updatedAt: "2022-11-18T11:47:49Z",
            isFork: true,
            isPrivate: false,
            isTemplate: false,
            isArchived: false,
            isEmpty: false,
            forkCount: 0,
            stargazerCount: 0,
            viewerCanUpdateTopics: true,
            viewerCanAdminister: true,
            repositoryTopics: {
              nodes: [],
            },
          },
        },
        {
          cursor: "Y3Vyc29yOnYyOpHOIKq5Cw==",
          node: {
            id: "R_kgDOIKq5Cw",
            name: "gittyhub",
            viewerPermission: "ADMIN",
            nameWithOwner: "tigawanna/gittyhub",
            description: "github graphql api + relay + react location",
            url: "https://github.com/tigawanna/gittyhub",
            openGraphImageUrl:
              "https://repository-images.githubusercontent.com/548059403/20301a20-8dc3-4657-8e48-b57dfd54a751",
            updatedAt: "2022-10-09T03:07:03Z",
            isFork: false,
            isPrivate: false,
            isTemplate: false,
            isArchived: false,
            isEmpty: false,
            forkCount: 0,
            stargazerCount: 0,
            viewerCanUpdateTopics: true,
            viewerCanAdminister: true,
            repositoryTopics: {
              nodes: [],
            },
          },
        },
        {
          cursor: "Y3Vyc29yOnYyOpHOILi0gw==",
          node: {
            id: "R_kgDOILi0gw",
            name: "pocketbase-app",
            viewerPermission: "ADMIN",
            nameWithOwner: "tigawanna/pocketbase-app",
            description:
              "redoing a firebase app in pocketbase + react-router + react-query + google-oauth",
            url: "https://github.com/tigawanna/pocketbase-app",
            openGraphImageUrl:
              "https://opengraph.githubassets.com/2bca3cf71d5f58418ea0e1b6712376a87592bf994bddae2269cdf723877d0e83/tigawanna/pocketbase-app",
            updatedAt: "2023-02-14T03:49:19Z",
            isFork: false,
            isPrivate: false,
            isTemplate: false,
            isArchived: false,
            isEmpty: false,
            forkCount: 1,
            stargazerCount: 3,
            viewerCanUpdateTopics: true,
            viewerCanAdminister: true,
            repositoryTopics: {
              nodes: [],
            },
          },
        },
        {
          cursor: "Y3Vyc29yOnYyOpHOIL4b7w==",
          node: {
            id: "R_kgDOIL4b7w",
            name: "kata-machine",
            viewerPermission: "ADMIN",
            nameWithOwner: "tigawanna/kata-machine",
            description:
              "typescript data structures and algorithms with primeagen",
            url: "https://github.com/tigawanna/kata-machine",
            openGraphImageUrl:
              "https://opengraph.githubassets.com/298402d89296f57516138eafd47087871b4c4da30b31ef10605cb53d1ef058a9/tigawanna/kata-machine",
            updatedAt: "2022-10-11T02:51:11Z",
            isFork: true,
            isPrivate: false,
            isTemplate: false,
            isArchived: false,
            isEmpty: false,
            forkCount: 0,
            stargazerCount: 0,
            viewerCanUpdateTopics: true,
            viewerCanAdminister: true,
            repositoryTopics: {
              nodes: [],
            },
          },
        },
        {
          cursor: "Y3Vyc29yOnYyOpHOIPbhYg==",
          node: {
            id: "R_kgDOIPbhYg",
            name: "pocket-base-project",
            viewerPermission: "ADMIN",
            nameWithOwner: "tigawanna/pocket-base-project",
            description: null,
            url: "https://github.com/tigawanna/pocket-base-project",
            openGraphImageUrl:
              "https://opengraph.githubassets.com/5b79e8d9be1a780514ed423576974fd1e500a05bafff2165296939218a286c4b/tigawanna/pocket-base-project",
            updatedAt: "2023-04-27T05:17:50Z",
            isFork: false,
            isPrivate: false,
            isTemplate: false,
            isArchived: false,
            isEmpty: false,
            forkCount: 0,
            stargazerCount: 4,
            viewerCanUpdateTopics: true,
            viewerCanAdminister: true,
            repositoryTopics: {
              nodes: [],
            },
          },
        },
        {
          cursor: "Y3Vyc29yOnYyOpHOIShCDw==",
          node: {
            id: "R_kgDOIShCDw",
            name: "vite-table",
            viewerPermission: "ADMIN",
            nameWithOwner: "tigawanna/vite-table",
            description: null,
            url: "https://github.com/tigawanna/vite-table",
            openGraphImageUrl:
              "https://opengraph.githubassets.com/54424f605632c1de6fa5be653754081df831fff252ed6743ff1cab379823963e/tigawanna/vite-table",
            updatedAt: "2022-10-23T14:04:29Z",
            isFork: false,
            isPrivate: false,
            isTemplate: false,
            isArchived: false,
            isEmpty: false,
            forkCount: 0,
            stargazerCount: 0,
            viewerCanUpdateTopics: true,
            viewerCanAdminister: true,
            repositoryTopics: {
              nodes: [],
            },
          },
        },
        {
          cursor: "Y3Vyc29yOnYyOpHOIVPUCg==",
          node: {
            id: "R_kgDOIVPUCg",
            name: "AirBnB_clone_v4",
            viewerPermission: "ADMIN",
            nameWithOwner: "tigawanna/AirBnB_clone_v4",
            description: "tigawanna cohort 5 AirBnB_clone_v4 ",
            url: "https://github.com/tigawanna/AirBnB_clone_v4",
            openGraphImageUrl:
              "https://opengraph.githubassets.com/00053dd2967c4e153dd4df20ab4a4862e9c86eab05272d7fbfe0eed5d31348ff/tigawanna/AirBnB_clone_v4",
            updatedAt: "2022-10-29T07:34:43Z",
            isFork: true,
            isPrivate: false,
            isTemplate: false,
            isArchived: false,
            isEmpty: false,
            forkCount: 0,
            stargazerCount: 0,
            viewerCanUpdateTopics: true,
            viewerCanAdminister: true,
            repositoryTopics: {
              nodes: [],
            },
          },
        },
        {
          cursor: "Y3Vyc29yOnYyOpHOIYUThA==",
          node: {
            id: "R_kgDOIYUThA",
            name: "pocketbase-carbuddy",
            viewerPermission: "ADMIN",
            nameWithOwner: "tigawanna/pocketbase-carbuddy",
            description: "all car buddies at your fingertips",
            url: "https://github.com/tigawanna/pocketbase-carbuddy",
            openGraphImageUrl:
              "https://opengraph.githubassets.com/480464812d848ca289454f6b79031272313dc92972ea36dddfa04dfe70d0e343/tigawanna/pocketbase-carbuddy",
            updatedAt: "2022-11-03T17:09:43Z",
            isFork: true,
            isPrivate: false,
            isTemplate: false,
            isArchived: false,
            isEmpty: false,
            forkCount: 0,
            stargazerCount: 0,
            viewerCanUpdateTopics: true,
            viewerCanAdminister: true,
            repositoryTopics: {
              nodes: [],
            },
          },
        },
        {
          cursor: "Y3Vyc29yOnYyOpHOIYY7EQ==",
          node: {
            id: "R_kgDOIYY7EQ",
            name: "AllEmpsAPIs",
            viewerPermission: "WRITE",
            nameWithOwner: "marcrine-geek/AllEmpsAPIs",
            description: "Endpoints for allemps apllication",
            url: "https://github.com/marcrine-geek/AllEmpsAPIs",
            openGraphImageUrl:
              "https://opengraph.githubassets.com/54d44a3c636926a0ac66e36d1dc15fab7c7b101eca6fd67584d384b64e775245/marcrine-geek/AllEmpsAPIs",
            updatedAt: "2022-12-14T11:13:18Z",
            isFork: false,
            isPrivate: false,
            isTemplate: false,
            isArchived: false,
            isEmpty: false,
            forkCount: 1,
            stargazerCount: 1,
            viewerCanUpdateTopics: false,
            viewerCanAdminister: false,
            repositoryTopics: {
              nodes: [],
            },
          },
        },
        {
          cursor: "Y3Vyc29yOnYyOpHOIci90w==",
          node: {
            id: "R_kgDOIci90w",
            name: "ubuntu-scripts-and-config",
            viewerPermission: "ADMIN",
            nameWithOwner: "tigawanna/ubuntu-scripts-and-config",
            description: null,
            url: "https://github.com/tigawanna/ubuntu-scripts-and-config",
            openGraphImageUrl:
              "https://opengraph.githubassets.com/ac58f4e5b9a5ce09cda195737784fc14f581b106075c6f288f4341ccff5d1495/tigawanna/ubuntu-scripts-and-config",
            updatedAt: "2022-11-16T13:07:22Z",
            isFork: false,
            isPrivate: false,
            isTemplate: false,
            isArchived: false,
            isEmpty: false,
            forkCount: 0,
            stargazerCount: 0,
            viewerCanUpdateTopics: true,
            viewerCanAdminister: true,
            repositoryTopics: {
              nodes: [],
            },
          },
        },
        {
          cursor: "Y3Vyc29yOnYyOpHOId_cTQ==",
          node: {
            id: "R_kgDOId_cTQ",
            name: "setup-scripts",
            viewerPermission: "ADMIN",
            nameWithOwner: "tigawanna/setup-scripts",
            description: null,
            url: "https://github.com/tigawanna/setup-scripts",
            openGraphImageUrl:
              "https://opengraph.githubassets.com/7cc38e5d9d1c176b83ca8ab048866d7b71db6ff2b746b4605445b522a5f9dd3c/tigawanna/setup-scripts",
            updatedAt: "2022-11-20T06:15:04Z",
            isFork: false,
            isPrivate: false,
            isTemplate: false,
            isArchived: false,
            isEmpty: false,
            forkCount: 0,
            stargazerCount: 0,
            viewerCanUpdateTopics: true,
            viewerCanAdminister: true,
            repositoryTopics: {
              nodes: [],
            },
          },
        },
        {
          cursor: "Y3Vyc29yOnYyOpHOIeIE9g==",
          node: {
            id: "R_kgDOIeIE9g",
            name: "all-emps-vite",
            viewerPermission: "ADMIN",
            nameWithOwner: "tigawanna/all-emps-vite",
            description: null,
            url: "https://github.com/tigawanna/all-emps-vite",
            openGraphImageUrl:
              "https://opengraph.githubassets.com/d657d9beab1407778705dc48b5862b4a94e48b012d111afc6e602fa9bf68786b/tigawanna/all-emps-vite",
            updatedAt: "2022-11-21T04:23:48Z",
            isFork: false,
            isPrivate: false,
            isTemplate: false,
            isArchived: false,
            isEmpty: false,
            forkCount: 0,
            stargazerCount: 0,
            viewerCanUpdateTopics: true,
            viewerCanAdminister: true,
            repositoryTopics: {
              nodes: [],
            },
          },
        },
        {
          cursor: "Y3Vyc29yOnYyOpHOIggbVg==",
          node: {
            id: "R_kgDOIggbVg",
            name: "yelp-review",
            viewerPermission: "ADMIN",
            nameWithOwner: "tigawanna/yelp-review",
            description: null,
            url: "https://github.com/tigawanna/yelp-review",
            openGraphImageUrl:
              "https://opengraph.githubassets.com/87f8c1e4fb8dd1ea012f882bfc09e0e89b4e89d210f93ea0aa0448119d55f88a/tigawanna/yelp-review",
            updatedAt: "2022-11-26T17:22:29Z",
            isFork: false,
            isPrivate: false,
            isTemplate: false,
            isArchived: false,
            isEmpty: false,
            forkCount: 0,
            stargazerCount: 0,
            viewerCanUpdateTopics: true,
            viewerCanAdminister: true,
            repositoryTopics: {
              nodes: [],
            },
          },
        },
        {
          cursor: "Y3Vyc29yOnYyOpHOIgswSA==",
          node: {
            id: "R_kgDOIgswSA",
            name: "NewPipe",
            viewerPermission: "ADMIN",
            nameWithOwner: "tigawanna/NewPipe",
            description: "A libre lightweight streaming front-end for Android.",
            url: "https://github.com/tigawanna/NewPipe",
            openGraphImageUrl:
              "https://opengraph.githubassets.com/92efa008b3431fb890f4ea35267a7181acaca697777274b88705c0de586fe211/tigawanna/NewPipe",
            updatedAt: "2022-11-27T11:10:40Z",
            isFork: true,
            isPrivate: false,
            isTemplate: false,
            isArchived: false,
            isEmpty: false,
            forkCount: 0,
            stargazerCount: 0,
            viewerCanUpdateTopics: true,
            viewerCanAdminister: true,
            repositoryTopics: {
              nodes: [],
            },
          },
        },
        {
          cursor: "Y3Vyc29yOnYyOpHOIhMkQw==",
          node: {
            id: "R_kgDOIhMkQw",
            name: "meilisearch",
            viewerPermission: "ADMIN",
            nameWithOwner: "tigawanna/meilisearch",
            description:
              "A lightning-fast search engine that fits effortlessly into your apps, websites, and workflow.",
            url: "https://github.com/tigawanna/meilisearch",
            openGraphImageUrl:
              "https://opengraph.githubassets.com/5d27947b2b710e5369c0530dadf7f92b77f24906bd33d46e39eff4e14a9ff297/tigawanna/meilisearch",
            updatedAt: "2022-11-28T16:46:45Z",
            isFork: true,
            isPrivate: false,
            isTemplate: false,
            isArchived: false,
            isEmpty: false,
            forkCount: 0,
            stargazerCount: 0,
            viewerCanUpdateTopics: true,
            viewerCanAdminister: true,
            repositoryTopics: {
              nodes: [],
            },
          },
        },
        {
          cursor: "Y3Vyc29yOnYyOpHOIih8gQ==",
          node: {
            id: "R_kgDOIih8gQ",
            name: "all-emps-emps-web",
            viewerPermission: "ADMIN",
            nameWithOwner: "tigawanna/all-emps-emps-web",
            description: null,
            url: "https://github.com/tigawanna/all-emps-emps-web",
            openGraphImageUrl:
              "https://opengraph.githubassets.com/215bbcc77c857107a3ac70e2f81b97992ce927bf640a936f1d28f37fa76e8216/tigawanna/all-emps-emps-web",
            updatedAt: "2022-12-01T16:48:53Z",
            isFork: false,
            isPrivate: false,
            isTemplate: false,
            isArchived: false,
            isEmpty: false,
            forkCount: 0,
            stargazerCount: 0,
            viewerCanUpdateTopics: true,
            viewerCanAdminister: true,
            repositoryTopics: {
              nodes: [],
            },
          },
        },
        {
          cursor: "Y3Vyc29yOnYyOpHOIiiDvw==",
          node: {
            id: "R_kgDOIiiDvw",
            name: "all-emps-web",
            viewerPermission: "ADMIN",
            nameWithOwner: "tigawanna/all-emps-web",
            description: null,
            url: "https://github.com/tigawanna/all-emps-web",
            openGraphImageUrl:
              "https://opengraph.githubassets.com/f4b9e2da8a3dd920a880e29c957466147c4a734f07a577a0f3492893e9727ccd/tigawanna/all-emps-web",
            updatedAt: "2022-12-01T16:51:20Z",
            isFork: false,
            isPrivate: false,
            isTemplate: false,
            isArchived: false,
            isEmpty: false,
            forkCount: 0,
            stargazerCount: 0,
            viewerCanUpdateTopics: true,
            viewerCanAdminister: true,
            repositoryTopics: {
              nodes: [],
            },
          },
        },
        {
          cursor: "Y3Vyc29yOnYyOpHOIj-dxw==",
          node: {
            id: "R_kgDOIj-dxw",
            name: "project-supabase",
            viewerPermission: "ADMIN",
            nameWithOwner: "tigawanna/project-supabase",
            description: null,
            url: "https://github.com/tigawanna/project-supabase",
            openGraphImageUrl:
              "https://opengraph.githubassets.com/578e08724e6d5c1603560a0c2cfc15271c881c0caa4e470c55afbe1e34e186cd/tigawanna/project-supabase",
            updatedAt: "2023-02-01T12:53:08Z",
            isFork: false,
            isPrivate: false,
            isTemplate: false,
            isArchived: false,
            isEmpty: false,
            forkCount: 0,
            stargazerCount: 0,
            viewerCanUpdateTopics: true,
            viewerCanAdminister: true,
            repositoryTopics: {
              nodes: [],
            },
          },
        },
        {
          cursor: "Y3Vyc29yOnYyOpHOIl2CQg==",
          node: {
            id: "R_kgDOIl2CQg",
            name: "allemps",
            viewerPermission: "ADMIN",
            nameWithOwner: "tigawanna/allemps",
            description: null,
            url: "https://github.com/tigawanna/allemps",
            openGraphImageUrl:
              "https://opengraph.githubassets.com/dec30397cff7f9c2fd04a302b481f2b13382e513df96f173ac8ce19008251c88/tigawanna/allemps",
            updatedAt: "2022-12-10T17:29:45Z",
            isFork: false,
            isPrivate: false,
            isTemplate: false,
            isArchived: false,
            isEmpty: false,
            forkCount: 0,
            stargazerCount: 0,
            viewerCanUpdateTopics: true,
            viewerCanAdminister: true,
            repositoryTopics: {
              nodes: [],
            },
          },
        },
        {
          cursor: "Y3Vyc29yOnYyOpHOIpFXdA==",
          node: {
            id: "R_kgDOIpFXdA",
            name: "alx-backend-javascript",
            viewerPermission: "ADMIN",
            nameWithOwner: "tigawanna/alx-backend-javascript",
            description: "alx specialization alx-backend-javascript",
            url: "https://github.com/tigawanna/alx-backend-javascript",
            openGraphImageUrl:
              "https://opengraph.githubassets.com/0c12f383ee2710edbe8267048c18da0981e6e8f4a0e6f5907262f1252e108602/tigawanna/alx-backend-javascript",
            updatedAt: "2022-12-19T14:57:28Z",
            isFork: false,
            isPrivate: false,
            isTemplate: false,
            isArchived: false,
            isEmpty: false,
            forkCount: 0,
            stargazerCount: 0,
            viewerCanUpdateTopics: true,
            viewerCanAdminister: true,
            repositoryTopics: {
              nodes: [],
            },
          },
        },
        {
          cursor: "Y3Vyc29yOnYyOpHOIpkMWQ==",
          node: {
            id: "R_kgDOIpkMWQ",
            name: "tsdx",
            viewerPermission: "ADMIN",
            nameWithOwner: "tigawanna/tsdx",
            description: "Zero-config CLI for TypeScript package development",
            url: "https://github.com/tigawanna/tsdx",
            openGraphImageUrl:
              "https://opengraph.githubassets.com/e87fe4cf177d6de2a31e94d3f0017145f5bb11b647ca59e81535ffb5159fab49/tigawanna/tsdx",
            updatedAt: "2022-12-20T14:39:57Z",
            isFork: true,
            isPrivate: false,
            isTemplate: false,
            isArchived: false,
            isEmpty: false,
            forkCount: 0,
            stargazerCount: 0,
            viewerCanUpdateTopics: true,
            viewerCanAdminister: true,
            repositoryTopics: {
              nodes: [],
            },
          },
        },
        {
          cursor: "Y3Vyc29yOnYyOpHOIqGhOQ==",
          node: {
            id: "R_kgDOIqGhOQ",
            name: "react-component-library-builder",
            viewerPermission: "ADMIN",
            nameWithOwner: "tigawanna/react-component-library-builder",
            description:
              "A project skeleton to get your very own React Component Library up and running using Rollup, Typescript, SASS + Storybook ",
            url: "https://github.com/tigawanna/react-component-library-builder",
            openGraphImageUrl:
              "https://opengraph.githubassets.com/5cede92021e221f63e7a8034ff006819a4bcd8fc72483d059975645ddb2158a8/tigawanna/react-component-library-builder",
            updatedAt: "2022-12-26T15:28:12Z",
            isFork: true,
            isPrivate: false,
            isTemplate: true,
            isArchived: false,
            isEmpty: false,
            forkCount: 0,
            stargazerCount: 0,
            viewerCanUpdateTopics: true,
            viewerCanAdminister: true,
            repositoryTopics: {
              nodes: [],
            },
          },
        },
        {
          cursor: "Y3Vyc29yOnYyOpHOIqIfSA==",
          node: {
            id: "R_kgDOIqIfSA",
            name: "alx-interview",
            viewerPermission: "ADMIN",
            nameWithOwner: "tigawanna/alx-interview",
            description: null,
            url: "https://github.com/tigawanna/alx-interview",
            openGraphImageUrl:
              "https://opengraph.githubassets.com/dbc129ad6f8b5d5a41fc3e1c78de8301f29fe1ab73ad1718a1aad9d8856291e7/tigawanna/alx-interview",
            updatedAt: "2022-12-22T06:21:06Z",
            isFork: false,
            isPrivate: false,
            isTemplate: false,
            isArchived: false,
            isEmpty: false,
            forkCount: 0,
            stargazerCount: 0,
            viewerCanUpdateTopics: true,
            viewerCanAdminister: true,
            repositoryTopics: {
              nodes: [],
            },
          },
        },
        {
          cursor: "Y3Vyc29yOnYyOpHOIqf9Dg==",
          node: {
            id: "R_kgDOIqf9Dg",
            name: "marmot-setup",
            viewerPermission: "ADMIN",
            nameWithOwner: "tigawanna/marmot-setup",
            description: null,
            url: "https://github.com/tigawanna/marmot-setup",
            openGraphImageUrl:
              "https://opengraph.githubassets.com/a007ca0ac2d5fd077013c09d4c4db058a21c25d4f4400f899a222879318b954c/tigawanna/marmot-setup",
            updatedAt: "2022-12-23T07:12:45Z",
            isFork: false,
            isPrivate: false,
            isTemplate: false,
            isArchived: false,
            isEmpty: false,
            forkCount: 0,
            stargazerCount: 0,
            viewerCanUpdateTopics: true,
            viewerCanAdminister: true,
            repositoryTopics: {
              nodes: [],
            },
          },
        },
        {
          cursor: "Y3Vyc29yOnYyOpHOIq74lQ==",
          node: {
            id: "R_kgDOIq74lQ",
            name: "saucy-boi",
            viewerPermission: "ADMIN",
            nameWithOwner: "tigawanna/saucy-boi",
            description: null,
            url: "https://github.com/tigawanna/saucy-boi",
            openGraphImageUrl:
              "https://avatars.githubusercontent.com/u/72096712?s=400&v=4",
            updatedAt: "2022-12-31T12:13:14Z",
            isFork: false,
            isPrivate: true,
            isTemplate: false,
            isArchived: false,
            isEmpty: false,
            forkCount: 0,
            stargazerCount: 0,
            viewerCanUpdateTopics: true,
            viewerCanAdminister: true,
            repositoryTopics: {
              nodes: [],
            },
          },
        },
        {
          cursor: "Y3Vyc29yOnYyOpHOIrYoSA==",
          node: {
            id: "R_kgDOIrYoSA",
            name: "tiny-pkgs",
            viewerPermission: "ADMIN",
            nameWithOwner: "tigawanna/tiny-pkgs",
            description:
              "collection of custom react packages and wrappers i commonly use",
            url: "https://github.com/tigawanna/tiny-pkgs",
            openGraphImageUrl:
              "https://opengraph.githubassets.com/7b3cbae59852f8764d653a11245d55647bf5d0e40bf1fc9bf2c94a553261c81f/tigawanna/tiny-pkgs",
            updatedAt: "2022-12-26T18:25:28Z",
            isFork: false,
            isPrivate: false,
            isTemplate: false,
            isArchived: false,
            isEmpty: false,
            forkCount: 0,
            stargazerCount: 0,
            viewerCanUpdateTopics: true,
            viewerCanAdminister: true,
            repositoryTopics: {
              nodes: [],
            },
          },
        },
        {
          cursor: "Y3Vyc29yOnYyOpHOIrw48A==",
          node: {
            id: "R_kgDOIrw48A",
            name: "form-pkg",
            viewerPermission: "ADMIN",
            nameWithOwner: "tigawanna/form-pkg",
            description:
              "custom react form with radix react-aria and react hook form for accessibility ",
            url: "https://github.com/tigawanna/form-pkg",
            openGraphImageUrl:
              "https://opengraph.githubassets.com/83178f98872eae1bde0c1b7d436d0f568cee1e9465e730e66b02657037b8d8ec/tigawanna/form-pkg",
            updatedAt: "2022-12-27T19:47:00Z",
            isFork: false,
            isPrivate: false,
            isTemplate: false,
            isArchived: false,
            isEmpty: false,
            forkCount: 0,
            stargazerCount: 0,
            viewerCanUpdateTopics: true,
            viewerCanAdminister: true,
            repositoryTopics: {
              nodes: [],
            },
          },
        },
        {
          cursor: "Y3Vyc29yOnYyOpHOIsFwBA==",
          node: {
            id: "R_kgDOIsFwBA",
            name: "react-select",
            viewerPermission: "ADMIN",
            nameWithOwner: "tigawanna/react-select",
            description: "The Select Component for React.js",
            url: "https://github.com/tigawanna/react-select",
            openGraphImageUrl:
              "https://opengraph.githubassets.com/f643df565e3c72d6a769b7f4cf113fc4c70c14b7c419d0509fbf21c4ca6ff3f9/tigawanna/react-select",
            updatedAt: "2022-12-28T19:17:38Z",
            isFork: true,
            isPrivate: false,
            isTemplate: false,
            isArchived: false,
            isEmpty: false,
            forkCount: 0,
            stargazerCount: 0,
            viewerCanUpdateTopics: true,
            viewerCanAdminister: true,
            repositoryTopics: {
              nodes: [],
            },
          },
        },
        {
          cursor: "Y3Vyc29yOnYyOpHOIsld5A==",
          node: {
            id: "R_kgDOIsld5A",
            name: "tinybase",
            viewerPermission: "ADMIN",
            nameWithOwner: "tigawanna/tinybase",
            description: "The reactive data store for local‑first apps.",
            url: "https://github.com/tigawanna/tinybase",
            openGraphImageUrl:
              "https://opengraph.githubassets.com/5d89516c01ae5c5853699837e99395fc91c912e95c367d991de9a625e66fa78c/tigawanna/tinybase",
            updatedAt: "2022-12-30T10:57:08Z",
            isFork: true,
            isPrivate: false,
            isTemplate: false,
            isArchived: false,
            isEmpty: false,
            forkCount: 0,
            stargazerCount: 0,
            viewerCanUpdateTopics: true,
            viewerCanAdminister: true,
            repositoryTopics: {
              nodes: [],
            },
          },
        },
        {
          cursor: "Y3Vyc29yOnYyOpHOIs2tFA==",
          node: {
            id: "R_kgDOIs2tFA",
            name: "react-virtuoso",
            viewerPermission: "ADMIN",
            nameWithOwner: "tigawanna/react-virtuoso",
            description: "The most powerful virtual list component for React",
            url: "https://github.com/tigawanna/react-virtuoso",
            openGraphImageUrl:
              "https://opengraph.githubassets.com/f01d6ac88aee85f261e41609e2eec0ad87429ef1a6e65e87cfd49cdaaf9e2594/tigawanna/react-virtuoso",
            updatedAt: "2022-12-31T11:52:33Z",
            isFork: true,
            isPrivate: false,
            isTemplate: false,
            isArchived: false,
            isEmpty: false,
            forkCount: 0,
            stargazerCount: 0,
            viewerCanUpdateTopics: true,
            viewerCanAdminister: true,
            repositoryTopics: {
              nodes: [],
            },
          },
        },
        {
          cursor: "Y3Vyc29yOnYyOpHOItNL7A==",
          node: {
            id: "R_kgDOItNL7A",
            name: "react-ts-form",
            viewerPermission: "ADMIN",
            nameWithOwner: "tigawanna/react-ts-form",
            description: "type dfae react form with react-hook-form and zod",
            url: "https://github.com/tigawanna/react-ts-form",
            openGraphImageUrl:
              "https://opengraph.githubassets.com/5c3248d3743593b5ec8ac7bf64b77ad39604a9201d65a179cee65de863ed340c/tigawanna/react-ts-form",
            updatedAt: "2023-01-02T04:19:55Z",
            isFork: true,
            isPrivate: false,
            isTemplate: false,
            isArchived: false,
            isEmpty: false,
            forkCount: 0,
            stargazerCount: 0,
            viewerCanUpdateTopics: true,
            viewerCanAdminister: true,
            repositoryTopics: {
              nodes: [],
            },
          },
        },
        {
          cursor: "Y3Vyc29yOnYyOpHOItTGJw==",
          node: {
            id: "R_kgDOItTGJw",
            name: "foreach",
            viewerPermission: "ADMIN",
            nameWithOwner: "tigawanna/foreach",
            description: null,
            url: "https://github.com/tigawanna/foreach",
            openGraphImageUrl:
              "https://repository-images.githubusercontent.com/584369703/dbde84d0-f7c4-4c22-a0b2-d7e961534b8e",
            updatedAt: "2023-04-09T04:56:20Z",
            isFork: false,
            isPrivate: false,
            isTemplate: false,
            isArchived: false,
            isEmpty: false,
            forkCount: 0,
            stargazerCount: 2,
            viewerCanUpdateTopics: true,
            viewerCanAdminister: true,
            repositoryTopics: {
              nodes: [],
            },
          },
        },
        {
          cursor: "Y3Vyc29yOnYyOpHOIuWstA==",
          node: {
            id: "R_kgDOIuWstA",
            name: "alx-backend-python",
            viewerPermission: "ADMIN",
            nameWithOwner: "tigawanna/alx-backend-python",
            description: null,
            url: "https://github.com/tigawanna/alx-backend-python",
            openGraphImageUrl:
              "https://opengraph.githubassets.com/be179dc77ce2b2ba8a88d8dc427feed26bce4f8f768609b824d9c2bc8419c0ff/tigawanna/alx-backend-python",
            updatedAt: "2023-01-05T09:16:20Z",
            isFork: false,
            isPrivate: false,
            isTemplate: false,
            isArchived: false,
            isEmpty: false,
            forkCount: 0,
            stargazerCount: 0,
            viewerCanUpdateTopics: true,
            viewerCanAdminister: true,
            repositoryTopics: {
              nodes: [],
            },
          },
        },
        {
          cursor: "Y3Vyc29yOnYyOpHOIwjmbw==",
          node: {
            id: "R_kgDOIwjmbw",
            name: "alx-backend-storage",
            viewerPermission: "ADMIN",
            nameWithOwner: "tigawanna/alx-backend-storage",
            description: null,
            url: "https://github.com/tigawanna/alx-backend-storage",
            openGraphImageUrl:
              "https://opengraph.githubassets.com/48ff925587e8d20c3cd9df791e3c130d633dcf5b63e3c7ea6614c72b67ad8d50/tigawanna/alx-backend-storage",
            updatedAt: "2023-01-17T12:07:46Z",
            isFork: false,
            isPrivate: false,
            isTemplate: false,
            isArchived: false,
            isEmpty: false,
            forkCount: 0,
            stargazerCount: 0,
            viewerCanUpdateTopics: true,
            viewerCanAdminister: true,
            repositoryTopics: {
              nodes: [],
            },
          },
        },
        {
          cursor: "Y3Vyc29yOnYyOpHOIxaFJg==",
          node: {
            id: "R_kgDOIxaFJg",
            name: "react-rollup-boilerplate",
            viewerPermission: "ADMIN",
            nameWithOwner: "tigawanna/react-rollup-boilerplate",
            description:
              "Boilerplate for creating React component libraries, bundled with Rollup.js to ES6 Modules, React Styleguidist, Typescript",
            url: "https://github.com/tigawanna/react-rollup-boilerplate",
            openGraphImageUrl:
              "https://opengraph.githubassets.com/11acae1e2728d82124c14dab6ec8cc17a4632a6b06293bd5c4a5fc2a457f8735/tigawanna/react-rollup-boilerplate",
            updatedAt: "2023-01-13T18:03:23Z",
            isFork: true,
            isPrivate: false,
            isTemplate: false,
            isArchived: false,
            isEmpty: false,
            forkCount: 0,
            stargazerCount: 0,
            viewerCanUpdateTopics: true,
            viewerCanAdminister: true,
            repositoryTopics: {
              nodes: [],
            },
          },
        },
      ],
    },
  },
};
